# Generated by Django 4.1.3 on 2022-11-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonalds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='amount',
            field=models.IntegerField(db_column='amount', default=1),
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='amount',
            new_name='_amount',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='labour_contract',
            new_name='labor_contract',
        ),
    ]
